name: Docker Image CI for GHCR
on:
    push
jobs:
    build_and_pub:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Build and Push Image
              run: |
                docker login --username 0xgeorgemathew --password ${{secrets.GH_PAT}} ghcr.io
                docker build . --tag ghcr.io/0xgeorgemathew/foundationwatch:latest
                docker push ghcr.io/0xgeorgemathew/foundationwatch:latest
                

            