name: Docker Image CI for GHCR
on:
  push:
    branches:
      - main # Or your desired branch to trigger the workflow

jobs:
  build_and_pub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Adjust Node.js version as needed

      - name: Install Dependencies
        run: npm install

      - name: Build (Transpile TypeScript)
        run: npm run build # Assuming you have a 'build' script in package.json

      - name: Build and Push Image
        run: |
          docker login --username 0xgeorgemathew --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . --tag ghcr.io/0xgeorgemathew/foundationwatch:latest
          docker push ghcr.io/0xgeorgemathew/foundationwatch:latest
      - name: Deploy To Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            docker pull ghcr.io/0xgeorgemathew/foundationwatch:latest
            docker stop foundationwatch || true
            docker rm foundationwatch || true
            docker run -d -e ${{ secrets.RPC_URL_HTTPS }} -e ${{ secrets.RPC_URL_WSS }} -e ${{ secrets.TELEGRAM_BOT_TOKEN }} -e ${{ secrets.WATCH_ADDRESS }} --name foundationwatch --restart unless-stopped ghcr.io/0xgeorgemathew/foundationwatch:latest
